[project]
name = "vobiz_ai"
version = "0.0.1"
description = "Vobiz AI telephony integration for ERPNext and Frappe CRM"
authors = [
    { name = "SRIAAS", email = "webdevelopersriaas@gmail.com" }
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "livekit-api>=1.1.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
